



[default]
APP_VERSION = "1.0.0"
REDIS_URL = "redis://localhost:6379/0"

[jwt]
SECRET_KEY = "super-secret"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRY_MINUTES = 30

[database]
HOST = "localhost"
PORT = 5432
USER = "dbuser"
PASSWORD = "dbpass"
NAME = "limebikemain"
COCKROACH_DB_PORT = 26257


[development]
SPICEDB_BEARER_TOKEN_KEY = "dev"
SPICEDB_ENDPOINT = "localhost:50051"
PORT = 5432
SPICEDB_INSECURE_CONF = "True"
REDIS_URL = "redis://localhost:6379/0"



[development.database]
HOST = "localhost"
PORT = 5432
SPICEDB_BEARER_TOKEN_KEY = "dev"
SPICEDB_ENDPOINT = "localhost:50051"
SPICEDB_INSECURE_CONF = "True"

[staging]
SPICEDB_BEARER_TOKEN_KEY = "dev"
SPICEDB_ENDPOINT = "localhost:50051"
PORT = 6000

[production]
SPICEDB_ENDPOINT = "grpc.authzed.com:443"
SPICEDB_BEARER_TOKEN_KEY = "prod"
PORT = 5432
COCKROACH_DB_PORT = 26257
COCKROACH_DB_ADMIN_UI = 8080
SPICEDB_INSECURE_CONF = "False"
REDIS_URL = "redis://:yourpassword@prod-redis-host:6379/0"
